service: cart-service-tatsiana-helakhava

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  
  profile: js-cc4
  region: eu-central-1
  iam:
    role:
      permissionsBoundary: 'arn:aws:iam::${aws:accountId}:policy/eo_role_boundary'

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true