service: cart-service-tatsiana-helakhava

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}

  profile: js-cc4
  region: eu-central-1

  vpc:
    securityGroupIds:
      - 'sg-02046ca8c1f7f5d46'
      - 'sg-02046ca8c1f7f5d46'
    subnetIds:
      - 'subnet-7d955331'
      - 'subnet-0417926e'
      - 'subnet-cb5aaab7'

  iam:
    role:
      permissionsBoundary: 'arn:aws:iam::${aws:accountId}:policy/eo_role_boundary'

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
